nav:
- Strona g贸wna: index.md
- Lekcje podstawowe:
  - 'Lekcja 1: Podstawy jzyka norweskiego': lekcje-podstawowe/lekcja-01.md
  - 'Lekcja 2: Jzyki i liczebniki': lekcje-podstawowe/lekcja-02.md
  - 'Lekcja 3: Rodzina i czas': lekcje-podstawowe/lekcja-03.md
  - 'Lekcja 4: Zaimki': lekcje-podstawowe/lekcja-04.md
  - 'Lekcja 5: Liczebniki i zwroty': lekcje-podstawowe/lekcja-05.md
  - 'Lekcja 6: Kolory i rodzina': lekcje-podstawowe/lekcja-06.md
  - 'Lekcja 7: Godziny': lekcje-podstawowe/lekcja-07.md
  - 'Lekcja 8: Zawody i czynnoci': lekcje-podstawowe/lekcja-08.md
  - 'Lekcja 9: Pogoda i rzeczowniki': lekcje-podstawowe/lekcja-09.md
  - 'Lekcja 10: Czasowniki modalne': lekcje-podstawowe/lekcja-10.md
- Lekcje rednie:
  - 'Lekcja 11: Jedzenie': lekcje-srednie/lekcja-11.md
  - 'Lekcja 12: Liczba mnoga': lekcje-srednie/lekcja-12.md
  - 'Lekcja 13: Zaimki wskazujce': lekcje-srednie/lekcja-13.md
  - 'Lekcja 14: Podr贸偶e': lekcje-srednie/lekcja-14.md
  - 'Lekcja 15: Pory roku': lekcje-srednie/lekcja-15.md
  - 'Lekcja 16: Czasowniki i wymowa': lekcje-srednie/lekcja-16.md
  - 'Lekcja 17: Miesice': lekcje-srednie/lekcja-17.md
- Lekcje zaawansowane:
  - 'Lekcja 18: Czasy przesze': lekcje-zaawansowane/lekcja-18.md
  - 'Lekcja 19: Wska藕niki czas贸w': lekcje-zaawansowane/lekcja-19.md
  - 'Lekcja 20: wiczenia czas贸w': lekcje-zaawansowane/lekcja-20.md
  - 'Lekcja 21: Tekst praktyczny': lekcje-zaawansowane/lekcja-21.md
  - 'Lekcja 22: Sownictwo zaawansowane': lekcje-zaawansowane/lekcja-22.md
- Gramatyka:
  - Zaimki: gramatyka/zaimki.md
  - Czasowniki nieregularne: gramatyka/czasowniki-nieregularne.md
  - Stopniowanie przymiotnik贸w: gramatyka/stopniowanie-przymiotnikow.md
  - Rzeczowniki: gramatyka/rzeczowniki.md
  - Czas perfektum: gramatyka/czas-perfektum.md
  - Tryb rozkazujcy: gramatyka/tryb-rozkazujacy.md
- Sownictwo:
  - Podstawowe zwroty: slownictwo/podstawowe-zwroty.md
  - Liczebniki: slownictwo/liczebniki.md
  - Kolory: slownictwo/kolory.md
  - Rodzina: slownictwo/rodzina.md
  - Jedzenie: slownictwo/jedzenie.md
  - Godziny: slownictwo/godziny.md
  - Pogoda: slownictwo/pogoda.md
  - Pory roku: slownictwo/pory-roku.md
-  Gry i wiczenia:
  - Przegld gier: games/index.md
- wiczenia:
  - wiczenia podstawowe: cwiczenia/podstawowe.md
  - wiczenia gramatyczne: cwiczenia/gramatyczne.md
  - Dialogi praktyczne: cwiczenia/dialogi.md
  - Testy: cwiczenia/testy.md
- Dialogi:
  - Dialogi sytuacyjne: dialogi/sytuacyjne.md
- Kultura:
  - Norwegia i kultura: kultura/norwegia.md
- Pomocnicze:
  - Wymowa: pomocnicze/wymowa.md
  - Postpy w nauce: pomocnicze/postepy.md
  - Tabele gramatyczne: pomocnicze/tabele-gramatyczne.md
  - Sowniczek tematyczny: pomocnicze/slowniczek.md
site_description: Kompleksowy kurs norweskiego na podstawie lekcji 1-22
site_name: Kurs Jzyka Norweskiego - Franciszek
theme:
  language: pl
  name: material
  palette:
    accent: red
    primary: blue
    scheme: default
